/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `skill_difficulty` (
  `skillid` tinyint(3) NOT NULL DEFAULT 0,
  `difficulty` float NOT NULL DEFAULT 0,
  `name` varchar(32) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;
INSERT INTO `skill_difficulty` VALUES (0,15,'Skill1HBlunt');
INSERT INTO `skill_difficulty` VALUES (1,12,'Skill1HSlashing');
INSERT INTO `skill_difficulty` VALUES (2,12,'Skill2HBlunt');
INSERT INTO `skill_difficulty` VALUES (3,12,'Skill2HSlashing');
INSERT INTO `skill_difficulty` VALUES (4,6,'SkillAbjuration');
INSERT INTO `skill_difficulty` VALUES (5,6,'SkillAlteration');
INSERT INTO `skill_difficulty` VALUES (6,7,'SkillApplyPoison');
INSERT INTO `skill_difficulty` VALUES (7,12,'SkillArchery');
INSERT INTO `skill_difficulty` VALUES (8,3,'SkillBackstab');
INSERT INTO `skill_difficulty` VALUES (9,2,'SkillBindWound');
INSERT INTO `skill_difficulty` VALUES (10,3,'SkillBash');
INSERT INTO `skill_difficulty` VALUES (11,15,'SkillBlock');
INSERT INTO `skill_difficulty` VALUES (12,12,'SkillBrassInstruments');
INSERT INTO `skill_difficulty` VALUES (13,5,'SkillChanneling');
INSERT INTO `skill_difficulty` VALUES (14,6,'SkillConjuration');
INSERT INTO `skill_difficulty` VALUES (15,15,'SkillDefense');
INSERT INTO `skill_difficulty` VALUES (16,5,'SkillDisarm');
INSERT INTO `skill_difficulty` VALUES (17,7,'SkillDisarmTraps');
INSERT INTO `skill_difficulty` VALUES (18,6,'SkillDivination');
INSERT INTO `skill_difficulty` VALUES (19,15,'SkillDodge');
INSERT INTO `skill_difficulty` VALUES (20,10,'SkillDoubleAttack');
INSERT INTO `skill_difficulty` VALUES (21,8,'SkillDragonPunch');
INSERT INTO `skill_difficulty` VALUES (22,12,'SkillDualWield');
INSERT INTO `skill_difficulty` VALUES (23,8,'SkillEagleStrike');
INSERT INTO `skill_difficulty` VALUES (24,6,'SkillEvocation');
INSERT INTO `skill_difficulty` VALUES (25,5,'SkillFeignDeath');
INSERT INTO `skill_difficulty` VALUES (26,8,'SkillFlyingKick');
INSERT INTO `skill_difficulty` VALUES (27,9,'SkillForage');
INSERT INTO `skill_difficulty` VALUES (28,12,'SkillHandtoHand');
INSERT INTO `skill_difficulty` VALUES (29,5,'SkillHide');
INSERT INTO `skill_difficulty` VALUES (30,3,'SkillKick');
INSERT INTO `skill_difficulty` VALUES (31,9,'SkillMeditate');
INSERT INTO `skill_difficulty` VALUES (32,3,'SkillMend');
INSERT INTO `skill_difficulty` VALUES (33,12,'SkillOffense');
INSERT INTO `skill_difficulty` VALUES (34,15,'SkillParry');
INSERT INTO `skill_difficulty` VALUES (35,6,'SkillPickLock');
INSERT INTO `skill_difficulty` VALUES (36,12,'Skill1HPiercing');
INSERT INTO `skill_difficulty` VALUES (37,15,'SkillRiposte');
INSERT INTO `skill_difficulty` VALUES (38,8,'SkillRoundKick');
INSERT INTO `skill_difficulty` VALUES (39,7,'SkillSafeFall');
INSERT INTO `skill_difficulty` VALUES (40,9,'SkillSenseHeading');
INSERT INTO `skill_difficulty` VALUES (41,12,'SkillSinging');
INSERT INTO `skill_difficulty` VALUES (42,5,'SkillSneak');
INSERT INTO `skill_difficulty` VALUES (43,7,'SkillSpecializeAbjure');
INSERT INTO `skill_difficulty` VALUES (44,7,'SkillSpecializeAlteration');
INSERT INTO `skill_difficulty` VALUES (45,7,'SkillSpecializeConjuration');
INSERT INTO `skill_difficulty` VALUES (46,7,'SkillSpecializeDivination');
INSERT INTO `skill_difficulty` VALUES (47,7,'SkillSpecializeEvocation');
INSERT INTO `skill_difficulty` VALUES (48,9,'SkillPickPockets');
INSERT INTO `skill_difficulty` VALUES (49,12,'SkillStringedInstruments');
INSERT INTO `skill_difficulty` VALUES (50,18,'SkillSwimming');
INSERT INTO `skill_difficulty` VALUES (51,7,'SkillThrowing');
INSERT INTO `skill_difficulty` VALUES (52,8,'SkillTigerClaw');
INSERT INTO `skill_difficulty` VALUES (53,10,'SkillTracking');
INSERT INTO `skill_difficulty` VALUES (54,12,'SkillWindInstruments');
INSERT INTO `skill_difficulty` VALUES (55,8,'SkillFishing');
INSERT INTO `skill_difficulty` VALUES (56,2,'SkillMakePoison');
INSERT INTO `skill_difficulty` VALUES (57,2,'SkillTinkering');
INSERT INTO `skill_difficulty` VALUES (58,2,'SkillResearch');
INSERT INTO `skill_difficulty` VALUES (59,2,'SkillAlchemy');
INSERT INTO `skill_difficulty` VALUES (60,3,'SkillBaking');
INSERT INTO `skill_difficulty` VALUES (61,2,'SkillTailoring');
INSERT INTO `skill_difficulty` VALUES (62,7,'SkillSenseTraps');
INSERT INTO `skill_difficulty` VALUES (63,2,'SkillBlacksmithing');
INSERT INTO `skill_difficulty` VALUES (64,4,'SkillFletching');
INSERT INTO `skill_difficulty` VALUES (65,3,'SkillBrewing');
INSERT INTO `skill_difficulty` VALUES (66,7,'SkillAlcoholTolerance');
INSERT INTO `skill_difficulty` VALUES (67,28,'SkillBegging');
INSERT INTO `skill_difficulty` VALUES (68,4,'SkillJewelryMaking');
INSERT INTO `skill_difficulty` VALUES (69,4,'SkillPottery');
INSERT INTO `skill_difficulty` VALUES (70,12,'SkillPercussionInstruments');
INSERT INTO `skill_difficulty` VALUES (71,3,'SkillIntimidation');
INSERT INTO `skill_difficulty` VALUES (72,0,'SkillBerserking');
INSERT INTO `skill_difficulty` VALUES (73,3,'SkillTaunt');
INSERT INTO `skill_difficulty` VALUES (74,3,'SkillFrenzy');
