/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `spawn_conditions` (
  `zone` varchar(32) NOT NULL DEFAULT '',
  `id` mediumint(8) unsigned NOT NULL DEFAULT 1,
  `value` mediumint(9) NOT NULL DEFAULT 0,
  `onchange` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `name` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`zone`,`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;
INSERT INTO `spawn_conditions` VALUES ('burningwood',2,0,2,'Naxot');
INSERT INTO `spawn_conditions` VALUES ('commons',1,1,2,'CommonsNightMobs');
INSERT INTO `spawn_conditions` VALUES ('commons',2,0,2,'CommonsDayMobs');
INSERT INTO `spawn_conditions` VALUES ('corathus',1,0,2,'CorStartEvent');
INSERT INTO `spawn_conditions` VALUES ('corathus',2,1,2,'CorCourtyard');
INSERT INTO `spawn_conditions` VALUES ('corathus',3,1,2,'CorSporeAreaTrash');
INSERT INTO `spawn_conditions` VALUES ('corathus',4,1,2,'CorMinotaurAreaTrash');
INSERT INTO `spawn_conditions` VALUES ('corathus',5,1,2,'CorClockworkAreaTrash');
INSERT INTO `spawn_conditions` VALUES ('corathus',6,0,2,'CorSporeAreaTrashBossDead');
INSERT INTO `spawn_conditions` VALUES ('corathus',7,0,2,'CorMinotaurAreaTrashBossDead');
INSERT INTO `spawn_conditions` VALUES ('corathus',8,0,2,'CorClockworkAreaTrashBossDead');
INSERT INTO `spawn_conditions` VALUES ('corathus',9,1,2,'CorSporeBoss');
INSERT INTO `spawn_conditions` VALUES ('corathus',10,1,2,'CorMinotaurBoss');
INSERT INTO `spawn_conditions` VALUES ('corathus',11,1,2,'CorClockworkSpiderBoss');
INSERT INTO `spawn_conditions` VALUES ('corathus',12,1,2,'CorEventPhase3');
INSERT INTO `spawn_conditions` VALUES ('dawnshroud',1,1,2,'Sambata');
INSERT INTO `spawn_conditions` VALUES ('dawnshroud',2,1,2,'Rockhopper');
INSERT INTO `spawn_conditions` VALUES ('eastwastes',1,1,2,'Night');
INSERT INTO `spawn_conditions` VALUES ('everfrost',1,1,2,'EverfrostNight');
INSERT INTO `spawn_conditions` VALUES ('everfrost',2,0,2,'EverfrostDay');
INSERT INTO `spawn_conditions` VALUES ('greatdivide',1,1,1,'ColdainWar');
INSERT INTO `spawn_conditions` VALUES ('guildlobby',1,1,0,'Time Keeper');
INSERT INTO `spawn_conditions` VALUES ('hollowshade',1,1,2,'Post_VahShir');
INSERT INTO `spawn_conditions` VALUES ('hollowshade',2,1,2,'North_Owl');
INSERT INTO `spawn_conditions` VALUES ('hollowshade',3,1,2,'East_Wolf');
INSERT INTO `spawn_conditions` VALUES ('hollowshade',4,1,2,'South_Grimling');
INSERT INTO `spawn_conditions` VALUES ('hollowshade',5,1,2,'Post_Wolf');
INSERT INTO `spawn_conditions` VALUES ('hollowshade',6,1,2,'Post_Owl');
INSERT INTO `spawn_conditions` VALUES ('hollowshade',7,1,2,'Post_Grimling');
INSERT INTO `spawn_conditions` VALUES ('hollowshade',8,1,2,'North_Wolf');
INSERT INTO `spawn_conditions` VALUES ('hollowshade',9,1,2,'North_Grimling');
INSERT INTO `spawn_conditions` VALUES ('kithicor',1,1,2,'KithicorNight');
INSERT INTO `spawn_conditions` VALUES ('kithicor',2,0,2,'KithicorDay');
INSERT INTO `spawn_conditions` VALUES ('lakerathe',1,0,2,'RatheNightMobs');
INSERT INTO `spawn_conditions` VALUES ('lakerathe',2,1,2,'RatheDayMobs');
INSERT INTO `spawn_conditions` VALUES ('lfaydark',1,1,2,'lfaydarkNightMobs');
INSERT INTO `spawn_conditions` VALUES ('mischiefplane',1,1,2,'Theater');
INSERT INTO `spawn_conditions` VALUES ('northkarana',1,1,2,'NKaranaNightMobs');
INSERT INTO `spawn_conditions` VALUES ('northkarana',2,0,2,'NKaranaDayMobs');
INSERT INTO `spawn_conditions` VALUES ('oggok',1,1,2,'Gronk');
INSERT INTO `spawn_conditions` VALUES ('oggok',2,0,2,'Ryn ');
INSERT INTO `spawn_conditions` VALUES ('poeartha',1,0,2,'poe_dust_event');
INSERT INTO `spawn_conditions` VALUES ('poeartha',2,0,2,'poe_ stone_event');
INSERT INTO `spawn_conditions` VALUES ('poearthb',1,1,2,'rathecouncil');
INSERT INTO `spawn_conditions` VALUES ('pofire',1,0,2,'pofire_Fennin');
INSERT INTO `spawn_conditions` VALUES ('pofire',2,1,2,'pofire_Fennin');
INSERT INTO `spawn_conditions` VALUES ('pofire',3,0,2,'pofire_Guardian');
INSERT INTO `spawn_conditions` VALUES ('poinnovation',1,0,2,'poiend');
INSERT INTO `spawn_conditions` VALUES ('poinnovation',2,0,2,'poinendloot');
INSERT INTO `spawn_conditions` VALUES ('potactics',1,1,2,'PoTactics Stampede Event');
INSERT INTO `spawn_conditions` VALUES ('potimeb',1,0,2,'potimeb_phase5');
INSERT INTO `spawn_conditions` VALUES ('potimeb',2,0,2,'potimeb_p3wave1');
INSERT INTO `spawn_conditions` VALUES ('potimeb',3,0,2,'potimeb_p3wave2');
INSERT INTO `spawn_conditions` VALUES ('potimeb',4,0,2,'potimeb_p3wave3');
INSERT INTO `spawn_conditions` VALUES ('potimeb',5,0,2,'potimeb_p3wave4');
INSERT INTO `spawn_conditions` VALUES ('potimeb',6,0,2,'potimeb_p3wave5');
INSERT INTO `spawn_conditions` VALUES ('potimeb',7,0,2,'potimeb_p3wave6');
INSERT INTO `spawn_conditions` VALUES ('potimeb',8,0,2,'potimeb_p3wave7');
INSERT INTO `spawn_conditions` VALUES ('potimeb',9,0,2,'potimeb_p3wave8');
INSERT INTO `spawn_conditions` VALUES ('potimeb',10,0,2,'potimeb_phase2');
INSERT INTO `spawn_conditions` VALUES ('qey2hh1',1,1,2,'WKaranaNightMobs');
INSERT INTO `spawn_conditions` VALUES ('qey2hh1',2,0,2,'WKaranaDayMobs');
INSERT INTO `spawn_conditions` VALUES ('qeynos2',1,1,2,'NorthQeynosNight');
INSERT INTO `spawn_conditions` VALUES ('qeynos2',2,0,2,'NorthQeynosDay');
INSERT INTO `spawn_conditions` VALUES ('rathemtn',1,0,2,'Zephyl');
INSERT INTO `spawn_conditions` VALUES ('rathemtn',2,1,2,'Hasten');
INSERT INTO `spawn_conditions` VALUES ('riwwi',1,0,2,'stonemites');
INSERT INTO `spawn_conditions` VALUES ('riwwi',2,0,2,'nightwatchman');
INSERT INTO `spawn_conditions` VALUES ('sleeper',1,1,2,'Warders');
INSERT INTO `spawn_conditions` VALUES ('sleeper',2,0,2,'Ancients');
INSERT INTO `spawn_conditions` VALUES ('sncrematory',1,0,2,'named_trigger');
INSERT INTO `spawn_conditions` VALUES ('snlair',1,0,2,'named_trigger');
INSERT INTO `spawn_conditions` VALUES ('snlair',2,1,1,'event');
INSERT INTO `spawn_conditions` VALUES ('snlair',3,0,2,'flagging');
INSERT INTO `spawn_conditions` VALUES ('snplant',1,0,2,'');
INSERT INTO `spawn_conditions` VALUES ('snplant',2,0,2,'');
INSERT INTO `spawn_conditions` VALUES ('snpool',1,0,2,'');
INSERT INTO `spawn_conditions` VALUES ('southkarana',1,1,2,'SKWerewolfNight');
INSERT INTO `spawn_conditions` VALUES ('southkarana',2,0,2,'SKSentryDay');
INSERT INTO `spawn_conditions` VALUES ('veeshan',1,0,2,'VeeshanOld');
INSERT INTO `spawn_conditions` VALUES ('veeshan',2,1,2,'VeeshanNew');
INSERT INTO `spawn_conditions` VALUES ('vxed',1,1,2,'Instance_Trigger');
INSERT INTO `spawn_conditions` VALUES ('qeynos',1,1,2,'QeynosNight');
INSERT INTO `spawn_conditions` VALUES ('qeynos',2,0,2,'QeynosDay');
INSERT INTO `spawn_conditions` VALUES ('qeytoqrg',1,1,2,'QeynosHillNight');
INSERT INTO `spawn_conditions` VALUES ('qeytoqrg',2,0,2,'QeynosHillDay');
INSERT INTO `spawn_conditions` VALUES ('freporte',1,1,2,'BarFreeportNight');
INSERT INTO `spawn_conditions` VALUES ('freporte',2,0,2,'BarFreeportDay');
INSERT INTO `spawn_conditions` VALUES ('overthere',1,1,2,'DragoonNight');
INSERT INTO `spawn_conditions` VALUES ('overthere',2,0,2,'DragoonDay');
INSERT INTO `spawn_conditions` VALUES ('thurgadinb',1,1,2,'ThurgbNight');
INSERT INTO `spawn_conditions` VALUES ('thurgadinb',2,0,2,'ThurgbDay');
INSERT INTO `spawn_conditions` VALUES ('fearplane',1,1,2,'Cazic_Spawned');
INSERT INTO `spawn_conditions` VALUES ('freporte',3,0,2,'Stormbreaker');
INSERT INTO `spawn_conditions` VALUES ('freporte',4,0,2,'SirensBane');
INSERT INTO `spawn_conditions` VALUES ('butcher',1,0,2,'Stormbreaker');
INSERT INTO `spawn_conditions` VALUES ('butcher',2,0,2,'SirensBane');
INSERT INTO `spawn_conditions` VALUES ('oot',1,0,2,'StormSirens');
INSERT INTO `spawn_conditions` VALUES ('oot',2,0,2,'SirensStorm');
INSERT INTO `spawn_conditions` VALUES ('erudnext',1,0,2,'Sea_King');
INSERT INTO `spawn_conditions` VALUES ('erudnext',2,0,2,'Golden_Maiden');
INSERT INTO `spawn_conditions` VALUES ('erudsxing',1,0,2,'Sea-Golden');
INSERT INTO `spawn_conditions` VALUES ('erudsxing',2,0,2,'Golden-Sea');
INSERT INTO `spawn_conditions` VALUES ('qeynos',3,0,2,'Sea_King');
INSERT INTO `spawn_conditions` VALUES ('qeynos',4,0,2,'Golden_Maiden');
INSERT INTO `spawn_conditions` VALUES ('lfaydark',2,0,2,'lfaydarkday');
INSERT INTO `spawn_conditions` VALUES ('steamfont',1,1,2,'Cargo');
INSERT INTO `spawn_conditions` VALUES ('neriakb',1,1,2,'NeriakBNight');
INSERT INTO `spawn_conditions` VALUES ('neriakb',2,0,2,'NeriakBDay');
INSERT INTO `spawn_conditions` VALUES ('fieldofbone',1,1,2,'FoBNight');
INSERT INTO `spawn_conditions` VALUES ('fieldofbone',2,0,2,'FoBDay');
INSERT INTO `spawn_conditions` VALUES ('soltemple',2,0,2,'SolTDay');
INSERT INTO `spawn_conditions` VALUES ('soltemple',1,1,2,'SolTNight');
INSERT INTO `spawn_conditions` VALUES ('neriakc',1,1,2,'TaniSpawn');
INSERT INTO `spawn_conditions` VALUES ('qey2hh1',3,0,2,'WKaranaGuardTrigger');
INSERT INTO `spawn_conditions` VALUES ('swampofnohope',1,1,2,'MysticDovan');
INSERT INTO `spawn_conditions` VALUES ('swampofnohope',2,0,2,'CaptainNedar');
INSERT INTO `spawn_conditions` VALUES ('firiona',1,1,2,'TrackerDay');
INSERT INTO `spawn_conditions` VALUES ('firiona',2,2,2,'TrackerNight');
INSERT INTO `spawn_conditions` VALUES ('timorous',1,0,2,'Maidens');
INSERT INTO `spawn_conditions` VALUES ('firiona',3,0,2,'Maidens');
INSERT INTO `spawn_conditions` VALUES ('timorous',2,0,2,'Barrel_Barge');
INSERT INTO `spawn_conditions` VALUES ('timorous',3,0,2,'Muckskimmer');
INSERT INTO `spawn_conditions` VALUES ('oasis',1,0,2,'Barrel_Barge');
INSERT INTO `spawn_conditions` VALUES ('oasis',2,0,2,'Muckskimmer');
INSERT INTO `spawn_conditions` VALUES ('overthere',3,0,2,'Bloated_belly');
INSERT INTO `spawn_conditions` VALUES ('timorous',4,0,2,'Bloated_Belly');
INSERT INTO `spawn_conditions` VALUES ('qcat',1,0,2,'CourierSpawn');
INSERT INTO `spawn_conditions` VALUES ('qcat',2,1,2,'MalkaSpawn');
INSERT INTO `spawn_conditions` VALUES ('kaladimb',1,1,2,'FounySpawn');
INSERT INTO `spawn_conditions` VALUES ('thurgadinb',3,1,2,'DainRepop');
INSERT INTO `spawn_conditions` VALUES ('iceclad',1,1,2,'pirate_runners_skiff');
INSERT INTO `spawn_conditions` VALUES ('nro',1,1,2,'pirate_runners_skiff');
INSERT INTO `spawn_conditions` VALUES ('akheva',1,0,2,'ItaerViusEvent');
INSERT INTO `spawn_conditions` VALUES ('thurgadina',1,1,1,'WarLost');
INSERT INTO `spawn_conditions` VALUES ('thurgadina',2,0,2,'DeadColdain');
INSERT INTO `spawn_conditions` VALUES ('thurgadinb',4,1,1,'WarLost');
INSERT INTO `spawn_conditions` VALUES ('thurgadinb',5,0,2,'DeadColdain');
INSERT INTO `spawn_conditions` VALUES ('gukbottom',1,1,2,'Raster');
INSERT INTO `spawn_conditions` VALUES ('gfaydark',1,1,2,'HendrickNight');
INSERT INTO `spawn_conditions` VALUES ('gfaydark',2,0,2,'HendrickDay');
INSERT INTO `spawn_conditions` VALUES ('highpass',1,1,2,'Night');
INSERT INTO `spawn_conditions` VALUES ('highpass',2,0,2,'Day');
INSERT INTO `spawn_conditions` VALUES ('hollowshade',10,1,2,'East_Owl');
INSERT INTO `spawn_conditions` VALUES ('hollowshade',11,1,2,'East_Grimling');
INSERT INTO `spawn_conditions` VALUES ('hollowshade',12,1,2,'South_Owl');
INSERT INTO `spawn_conditions` VALUES ('hollowshade',13,1,2,'South_Wolf');
INSERT INTO `spawn_conditions` VALUES ('tenebrous',1,1,2,'TenebrousNight');
INSERT INTO `spawn_conditions` VALUES ('tenebrous',2,0,2,'TenebrousDay');
INSERT INTO `spawn_conditions` VALUES ('sro',1,1,2,'SouthRoNight');
INSERT INTO `spawn_conditions` VALUES ('sro',2,0,2,'SouthRoDay');
INSERT INTO `spawn_conditions` VALUES ('grimling',6,1,0,'GrimlingWarCamps');
INSERT INTO `spawn_conditions` VALUES ('ssratemple',1,1,0,'BloodUp');
INSERT INTO `spawn_conditions` VALUES ('ssratemple',2,0,0,'GolemUp');
INSERT INTO `spawn_conditions` VALUES ('grimling',1,1,0,'Husman Camp');
INSERT INTO `spawn_conditions` VALUES ('grimling',2,1,0,'Danarin Camp');
INSERT INTO `spawn_conditions` VALUES ('grimling',3,1,0,'Derrin Camp');
INSERT INTO `spawn_conditions` VALUES ('grimling',4,1,0,'Necin Camps');
INSERT INTO `spawn_conditions` VALUES ('grimling',5,1,0,'Vadrel Camps');
INSERT INTO `spawn_conditions` VALUES ('cabeast',1,1,2,'CabeastNight');
INSERT INTO `spawn_conditions` VALUES ('cabeast',2,0,2,'CabeastDay');
INSERT INTO `spawn_conditions` VALUES ('katta',1,1,2,'KattaNight');
INSERT INTO `spawn_conditions` VALUES ('katta',2,0,2,'KattaDay');
INSERT INTO `spawn_conditions` VALUES ('postorms',1,1,0,'Cave Frogs');
INSERT INTO `spawn_conditions` VALUES ('gfaydark',3,1,2,'ExpinSpawn');
INSERT INTO `spawn_conditions` VALUES ('lakeofillomen',1,1,2,'LoioNight');
INSERT INTO `spawn_conditions` VALUES ('lakeofillomen',2,0,2,'LoioDay');
